### 
GET example.com

###
GET http://www.example.com

### Get one poste
GET https://jsonplaceholder.typicode.com/posts/3

### Delete one post
DELETE https://jsonplaceholder.typicode.com/posts/3

### GET https://jsonplaceholder.typicode.com/posts

### POST create one post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "New post!",
  "body": "This is my post!"
  }


### Put update one post
PUT https://jsonplaceholder.typicode.com/posts/2
Content-Type: application/json

{
  "title": "New post!"
  }

### Patch partial update one post
PATCH  https://jsonplaceholder.typicode.com/posts/3
Content-Type: application/json

{
  "title": "New post!"
  }

###
GET http://localhost:3000

### Aufgabe Express Request handler schreiben für POST, PUT, PATCH, DELETE (Route: /api/cards)
### Schauen, b es klappt:
GET http://localhost:3000/api/cards

###

GET http://localhost:3000/api/cards/12

###

POST http://localhost:3000/api/cards 
Content-Type: application/json

{
    "text": "What do yo want to know?",
    "author": "Jon Doe"  
}

###
PUT http://localhost:3000/api/cards/2
Content-Type: application/json

{
    
    "author": "Bob"
}


###
PATCH http://localhost:3000/api/cards/1
Content-Type: application/json

{
    "text": "This is a AWESOME patch text"
}

###
DELETE  http://localhost:3000/api/cards/2


