
GET http://localhost:3000/api/cards

###

GET http://localhost:3000/api/cards/61555b6205b81e952c62c936

###

POST http://localhost:3000/api/cards 
Content-Type: application/json

{
    "text": "What do yo want to know?",
    "author": "Jon Doe"  
}

###
PUT http://localhost:3000/api/cards/61555b6205b81e952c62c935
Content-Type: application/json

{
    "text": "New text",
    "author": "Bob"
}


###
PATCH http://localhost:3000/api/cards/61555b6205b81e952c62c935
Content-Type: application/json

{
    "text": "This is a AWESOME patch text"
}

###
DELETE  http://localhost:3000/api/cards/61543c481a0a0b23a3590e7e


